# Generated by Django 4.2.7 on 2026-01-19 14:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('solana_balance', models.FloatField(default=0.0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('equipment_type', models.CharField(choices=[('router', 'Маршрутизатор'), ('switch', 'Коммутатор'), ('server', 'Сервер'), ('cable', 'Кабель'), ('antenna', 'Антенна'), ('satellite', 'Спутник'), ('modem', 'Модем'), ('multiplexer', 'Мультиплексор')], max_length=50, verbose_name='Тип оборудования')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('power_consumption_w', models.IntegerField(default=0, verbose_name='Потребляемая мощность (Вт)')),
                ('throughput_gbps', models.FloatField(default=1, verbose_name='Пропускная способность (Гбит/с)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Изображение')),
                ('datasheet_url', models.URLField(blank=True, verbose_name='Ссылка на документацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='GlobeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_speed', models.FloatField(default=0.1, verbose_name='Скорость вращения')),
                ('auto_rotate', models.BooleanField(default=True, verbose_name='Автовращение')),
                ('show_equipment', models.BooleanField(default=True, verbose_name='Показывать оборудование')),
                ('show_cables', models.BooleanField(default=True, verbose_name='Показывать кабели')),
                ('zoom_level', models.FloatField(default=1.0, verbose_name='Уровень масштабирования')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('node_type', models.CharField(choices=[('city', 'Город'), ('datacenter', 'Дата-центр'), ('ix', 'Точка обмена (IX)'), ('cable_station', 'Кабельная станция')], max_length=50, verbose_name='Тип узла')),
                ('network_type', models.CharField(choices=[('existing', 'Существующая сеть'), ('proposed', 'Предлагаемая сеть')], default='existing', max_length=50, verbose_name='Тип сети')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('altitude', models.FloatField(default=0, verbose_name='Высота')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('capacity_gbps', models.FloatField(default=1, verbose_name='Пропускная способность (Гбит/с)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('source', models.CharField(max_length=200, verbose_name='Источник')),
                ('source_url', models.URLField(verbose_name='Ссылка на источник')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('infrastructure', 'Инфраструктура'), ('blockchain', 'Блокчейн'), ('satellite', 'Спутниковая связь'), ('research', 'Исследования'), ('general', 'Общее')], default='general', max_length=50, verbose_name='Категория')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Z96A', max_length=200, verbose_name='Название сайта')),
                ('primary_color', models.CharField(default='#2e2d2e', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#333135', max_length=7, verbose_name='Вторичный цвет')),
                ('accent_color', models.CharField(default='#1b1523', max_length=7, verbose_name='Акцентный цвет')),
                ('default_language', models.CharField(default='ru', max_length=10, verbose_name='Язык по умолчанию')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Режим обслуживания')),
            ],
        ),
        migrations.CreateModel(
            name='UserProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('proposal_type', models.CharField(choices=[('new_equipment', 'Новое оборудование'), ('upgrade', 'Обновление'), ('new_node', 'Новый узел'), ('new_connection', 'Новое соединение')], max_length=50, verbose_name='Тип предложения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('justification', models.TextField(blank=True, verbose_name='Обоснование')),
                ('solana_tx_signature', models.CharField(max_length=255, verbose_name='Подпись транзакции Solana')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('implemented', 'Реализовано')], default='pending', max_length=50, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('proposed_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipment', verbose_name='Предлагаемое оборудование')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.networknode', verbose_name='Целевой узел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='NodeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(default='operational', max_length=50, verbose_name='Статус')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment', verbose_name='Оборудование')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.networknode', verbose_name='Узел')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('connection_type', models.CharField(choices=[('undersea_cable', 'Подводный кабель'), ('terrestrial_fiber', 'Наземное волокно'), ('wireless', 'Беспроводное'), ('satellite', 'Спутниковое')], max_length=50, verbose_name='Тип соединения')),
                ('length_km', models.FloatField(default=0, verbose_name='Длина (км)')),
                ('capacity_gbps', models.FloatField(default=1, verbose_name='Пропускная способность (Гбит/с)')),
                ('latency_ms', models.FloatField(default=10, verbose_name='Задержка (мс)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('geojson_path', models.JSONField(blank=True, default=dict, verbose_name='GeoJSON путь')),
                ('equipment_used', models.ManyToManyField(blank=True, to='core.equipment', verbose_name='Используемое оборудование')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='core.networknode', verbose_name='Из узла')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='core.networknode', verbose_name='В узел')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Голосов за')),
                ('downvotes', models.IntegerField(default=0, verbose_name='Голосов против')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CablePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='Порядковый номер')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='Глубина (м)')),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.networkconnection', verbose_name='Кабель')),
            ],
            options={
                'ordering': ['cable', 'sequence'],
            },
        ),
    ]
