# Generated by Django 5.0.6 on 2024-01-19 12:30:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchaintransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blockchain Transaction', 'verbose_name_plural': 'Blockchain Transactions'},
        ),
        migrations.AddField(
            model_name='cable',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cables', to='core.region'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('wallet_address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('public_key', models.TextField(blank=True)),
                ('private_key_encrypted', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_spent', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('discussions_count', models.IntegerField(default=0)),
                ('transactions_count', models.IntegerField(default=0)),
                ('email_notifications', models.BooleanField(default=True)),
                ('newsletter_subscription', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('cables_favorited', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.cable')),
                ('cables_viewed', models.ManyToManyField(blank=True, related_name='viewed_by', to='core.cable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['wallet_address'], name='core_userpr_wallet__2266e0_idx'), models.Index(fields=['balance'], name='core_userpr_balance_f6886e_idx'), models.Index(fields=['user', 'is_verified'], name='core_userpr_user_id_a2af4d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'created_at'], name='core_system_user_id_8c5cd4_idx'),
        ),
    ]