# Generated by Django 4.2.11 on 2026-01-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cable_type', models.CharField(choices=[('submarine', 'Подводный'), ('terrestrial', 'Наземный')], max_length=20)),
                ('capacity', models.CharField(blank=True, max_length=50)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('owners', models.JSONField(default=list)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#1e90ff', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кабель',
                'verbose_name_plural': 'Кабели',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterModelOptions(
            name='blockchaintransaction',
            options={'verbose_name': 'Блокчейн транзакция', 'verbose_name_plural': 'Блокчейн транзакции'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='networkconnection',
            options={'verbose_name': 'Соединение', 'verbose_name_plural': 'Соединения'},
        ),
        migrations.AlterModelOptions(
            name='networkelement',
            options={'verbose_name': 'Сетевой элемент', 'verbose_name_plural': 'Сетевые элементы'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='element_type',
            field=models.CharField(choices=[('satellite', 'Спутник'), ('ground_station', 'Наземная станция'), ('router', 'Маршрутизатор'), ('switch', 'Коммутатор'), ('server', 'Сервер'), ('cable', 'Кабель'), ('user_device', 'Пользовательское устройство'), ('core_router', 'Core Router (Магистральный)'), ('ix', 'Internet Exchange (IX)'), ('olt', 'OLT (Optical Line Terminal)'), ('dslam', 'DSLAM'), ('multiplexer', 'Мультиплексор'), ('modem', 'Модем'), ('base_station', 'Базовая станция'), ('data_center', 'Центр обработки данных'), ('repeater', 'Ретранслятор')], max_length=20),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.region')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_type', models.CharField(choices=[('capital', 'Столица'), ('major', 'Крупный город'), ('hub', 'Сетевой хаб'), ('regional', 'Региональный центр')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.IntegerField(blank=True, null=True)),
                ('is_hub', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='networkelement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_elements', to='core.city'),
        ),
        migrations.CreateModel(
            name='CableRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_name', models.CharField(max_length=200)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='core.cable')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
            ],
            options={
                'verbose_name': 'Точка маршрута кабеля',
                'verbose_name_plural': 'Точки маршрутов кабелей',
                'ordering': ['cable', 'order'],
                'unique_together': {('cable', 'order')},
            },
        ),
    ]
